[workspace]
members = ["paxos", "sync"]
resolver = "3"

[workspace.dependencies]
zerocopy = { version = "0.8", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
scopeguard = "1"
turmoil = "0.7"
tokio-util = { version = "0.7", features = ["codec"] }
bytes = "1"
rand = "0.9"
tokio-stream = { version = "0.1", features = ["sync"] }
