[workspace]
members = ["paxos", "sync"]

[workspace.dependencies]
zerocopy = { version = "0.8", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
scopeguard = "1"
